
Installation
=============

Before you can use the pytorch integration :ref:`make sure you have the optional dependencies installed <installation-pytorch>`.

Query Strategies
================

For list of query strategies included in pytorch integration see :doc:`Query Strategies</components/query_strategies>`.

Example
=======

A code example showing a pytorch multiclass classification is given in :file:`examples/examplecode/pytorch_multiclass_classification.py`.

.. literalinclude:: ../../examples/examplecode/pytorch_multiclass_classification.py
   :language: python
