version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

formats: []

python:
  version: "3.8"
  install:
  - method: pip
    path: .
    extra_requirements:
      - transformers
  - requirements: docs/requirements.txt
