.. py:currentmodule:: small_text.integrations.transformers

Dataset Classes
===============
.. autoclass:: small_text.integrations.transformers.datasets.TransformersDataset
    :inherited-members:
    :noindex:
    :special-members: __init__

Classification
==============

Transformer-based Classification
--------------------------------

.. autoclass:: small_text.integrations.transformers.classifiers.classification.FineTuningArguments
   :special-members: __init__
   :members:

.. autoclass:: small_text.integrations.transformers.classifiers.classification.TransformerBasedClassification
   :special-members: __init__
   :members:

Sentence Transformer Finetuning
-------------------------------

.. autoclass:: small_text.integrations.transformers.classifiers.setfit.SetFitModelArguments
   :special-members: __init__
   :members:

.. autoclass:: small_text.integrations.transformers.classifiers.setfit.SetFitClassification
   :special-members: __init__
   :members:
